### ISSUE TITLE
[Roadmap]: catBot reacts

### ISSUE THREAD

**Issue by mwinterstorm** [mwinterstorm/catBot#10]
# Overview
catBot emotes to certain messages

# To Do 
- [ ] [catBot reacts]: database to store reactions
- [ ] [catBot reacts]: emote when message includes reactions
- [ ] [catBot reacts]: dynamic emotes based on message context
- [ ] [catBot reacts]: admin page for adding / modifying reactions
