### ISSUE TITLE
[Roadmap]: catBot responds

### ISSUE THREAD

**Issue by mwinterstorm** [mwinterstorm/catBot#15]
# Overview
catBot will reply to certain messages

# To Do 
- [ ] [catBot responds]: database to store responses
- [ ] [catBot responds]: response logic
- [ ] [catBot responds]: admin page for managing
