### ISSUE TITLE
[Roadmap]: Use gps location from Home Assistant to get wttr

### ISSUE THREAD

**Issue by mwinterstorm** [mwinterstorm/catBot#26]
# Overview
Use gps location from Home Assistant to get wttr

# To Do 
- [ ] Home Assistant Integration
- [ ] Get location of user
- [ ] use to get wttr
