### ISSUE TITLE
[Roadmap]: fireApp integration

### ISSUE THREAD

**Issue by mwinterstorm** [mwinterstorm/catBot#34]
# Overview
Integrate with fireApp

# To Do 
- [ ] [fireApp integration]: Limit who can call the function
- [ ] [fireApp integration]: ask for current position
- [ ] [fireApp integration]: alert on significant changes
- [ ] [fireApp integration]: send daily summary of changes / position
