### ISSUE TITLE
[Roadmap]: Home Assistant

### ISSUE THREAD

**Issue by mwinterstorm** [mwinterstorm/catBot#40]
# Overview
Integration with Home Assistant

# To Do 
- [ ] [Home Assistant]: Get Mark / Marissa Location
- [ ] [Home Assistant]: Use for getting weather #26 
- [ ] [Home Assistant]: integrate with HA assist
