### ISSUE TITLE
[Roadmap]: Nightscout

### ISSUE THREAD

**Issue by mwinterstorm** [mwinterstorm/catBot#5]
# Overview
Integration with Nightscout

# To Do 

- [ ] Connect to nightscout
- [ ] Get current sugar and respond
- [ ] Get recent sugar graph and respond
- [ ] Automatic blood sugar alerts
